<?php
/**
 * MyBB 1.6 English Language Pack
 * Copyright 2012 Community MyBB Vietnam, All Rights Reserved
 * 
 * $Id: online.lang.php 5635 2012-02-27 08:45:33Z Community MyBB Vietnam $
 */

$l['nav_online'] = "Ai đang online";
$l['nav_onlinetoday'] = "Ai đã online hôm nay";

$l['viewing_announcements'] = "Đang xem thông báo của<a href=\"{1}\">{2}</a>";
$l['viewing_announcements2'] = "Đang xem thông báo của forum";
$l['viewing_attachment'] = "Đang xem file đính kèm";
$l['viewing_attachment2'] = "Đang xem <a href=\"attachment.php?aid={1}\" target=\"_blank\">file đính kèm</a> trong bài <a href=\"{3}\">{2}</a>";
$l['viewing_calendar'] = "Đang xem <a href=\"calendar.php\">lịch</a>";
$l['viewing_event'] = "Đang xem sự kiện";
$l['viewing_event2'] = "Đang xem sự kiện <a href=\"{1}\">{2}</a>";
$l['adding_event'] = "<a href=\"calendar.php?action=addevent\">Thêm sự kiện</a>";
$l['editing_event'] = "Chỉnh sửa sự kiện";
$l['editing_post'] = "Chỉnh sửa bài viết";
$l['viewing_forum'] = "Đang xem diễn đàn";
$l['viewing_forum2'] = "Đang xem diễn đàm <a href=\"{1}\">{2}</a>";
$l['forum_redirect_to'] = "Đang được chuyển đến <a href=\"{1}\">{2}</a>";
$l['viewing_index'] = "{1} <a href=\"index.php\">Trang chủ</a>";
$l['activating_account'] = "Đang kích hoạt tài khoản";
$l['viewing_profile'] = "Đang xem hồ sơ";
$l['viewing_profile2'] = "Đang xem hồ sơ của <a href=\"{1}\">{2}</a>";
$l['registering'] = "<a href=\"member.php?action=register\">Đăng đăng kí</a>";
$l['logging_in'] = "<a href=\"member.php?action=login\">Đang đăng nhập</a>";
$l['logging_in_plain'] = "Đang đăng nhập";
$l['logging_out'] = "Đang thoát";
$l['emailing_user'] = "Đang gửi email cho thành viên khác";
$l['rating_user'] = "Đang đánh giá thành viên khác";
$l['viewing_memberlist'] = "Đang xem <a href=\"memberlist.php\">danh sách thành viên</a>";
$l['viewing_whoposted'] = "Đang xem ai đã gửi bài";
$l['viewing_whoposted2'] = "Đang xem ai đã gửi bài trong chủ đề <a href=\"{1}\">{2}</a>";
$l['marking_read'] = "<a href=\"misc.php?action=markread\">Đánh dấu là đã đọc</a>";
$l['viewing_helpdocs'] = "Đang xem <a href=\"misc.php?action=help\">tài liệu giúp đỡ</a>";
$l['viewing_buddylist'] = "Đang xem <a href=\"misc.php?action=buddypopup\">danh sách bạn bè</a>";
$l['viewing_smilies'] = "Đang xem <a href=\"misc.php?action=smilies\">danh sách mặt cười</a>";
$l['viewing_syndication'] = "Đang xem <a href=\"misc.php?action=syndication\">RSS Syndication</a> Page";
$l['replying_thread'] = "Đang trả lời chủ đề";
$l['replying_thread2'] = "Đang trả lời chủ đề <a href=\"{1}\">{2}</a>";
$l['posting_thread'] = "Đang viết bài mới";
$l['posting_thread2'] = "Đang viết chủ đề mới trong <a href=\"{1}\">{2}</a>";
$l['viewing_wol'] = "Đang xem <a href=\"online.php\">ai đang online</a>";
$l['viewing_woltoday'] = "Đang xem <a href=\"online.php?action=today\">ai đã online hôm nay</a>";
$l['creating_poll'] = "Đang tạo bình chọn mới";
$l['editing_poll'] = "Đang chỉnh sửa bình chọn";
$l['viewing_pollresults'] = "Đang xem kết quả của bình chọn";
$l['voting_poll'] = "Đang bỏ phiếu cho bình chọn";
$l['using_modtools'] = "Đang sử dụng chức năng quản lí";
$l['sending_pm'] = "Đang gửi tin nhắn riêng";
$l['reading_pm'] = "Đang đọc tin nhắn riêng";
$l['editing_pmfolders'] = "Đang chỉnh sửa thư mục các tin nhắn";
$l['using_pmsystem'] = "Đang sử dụng hệ thống tin nhắn";
$l['reporting_post'] = "Đang báo cáo một bài viết";
$l['searching_forum'] = "<a href=\"search.php\">Đang tìm kiếm</a> {1}";
$l['reading_thread'] = "Đang đọc chủ đề";
$l['reading_thread2'] = "Đang đọc chủ đề <a href=\"{1}\">{2}</a> {3}";
$l['viewing_team'] = "Đang xem các nhóm của diễn đàn";
$l['viewing_stats'] = "Đang xem thống kê diễn đàn";
$l['updating_profile'] = "<a href=\"usercp.php?action=profile\">Đang cập nhật hồ sơ</a>";
$l['updating_options'] = "<a href=\"usercp.php?action=options\">Đang cập nhật các tùy chỉnh</a>";
$l['editing_signature'] = "<a href=\"usercp.php?action=editsig\">Đang chỉnh sửa chứ ký</a>";
$l['changing_avatar'] = "<a href=\"usercp.php?action=avatar\">Đang thay đổi ảnh đại diện</a>";
$l['viewing_subscriptions'] = "Đang xem <a href=\"usercp.php?action=subscriptions\">các chủ đề theo dõi</a>";
$l['viewing_favorites'] = "Đang xem <a href=\"usercp.php?action=favorites\">các chủ đề yêu thích</a>";
$l['editing_pad'] = "Đang chỉnh sửa <a href=\"usercp.php?action=notepad\">Personal Pad</a>";
$l['editing_password'] = "Đang thay đổi <a href=\"usercp.php?action=password\">mật mã</a>";
$l['user_cp'] = "Đang xem <a href=\"usercp.php\">bảng điều khiển cá nhân</a>";
$l['viewing_portal'] = "Đang xem <a href=\"portal.php\">Portal</a> Page";
$l['viewing_noperms'] = "Đang xem trang No Permissions";
$l['unknown_location'] = "<a href=\"{1}\">Không biết</a>";
$l['giving_reputation'] = "Đang cho danh tiếng <a href=\"{1}\">{2}</a>";
$l['viewing_reputation_report'] = "Đang xem <a href=\"{1}\">{2}'s Danh tiếng</a>";
$l['member_resendactivation'] = "Đang gửi lại email kích hoạt";
$l['member_lostpw'] = "Đang tìm lại <a href=\"member.php?action=lostpw\">mật khẩu</a>";
$l['sending_thread'] = "Đang gửi một chủ đề cho bạn";
$l['guest'] = "Khách";
$l['page'] = "Trang";
$l['users_online'] = "Ai đang online";
$l['on_username'] = "Thành viên";
$l['time'] = "Thời gian";
$l['location'] = "Địa điểm";
$l['online_today'] = "Ai đã online hôm nay";
$l['refresh_page'] = "Làm mới trang này";
$l['online_online_plural'] = "người dùng";
$l['online_online_singular'] = "người dùng";
$l['online_member_plural'] = "thành viên";
$l['online_member_singular'] = "thành vien";
$l['online_anon_plural'] = "đang";
$l['online_anon_singular'] = "đang";
$l['online_guest_plural'] = "khách";
$l['online_guest_singular'] = "khách";
$l['online_count'] = "{1} {2} hoạt động trong vòng {3} phút qua ({4} {5}, {6} người {7} ẩn, và {8} {9}).";
$l['ip'] = "IP:";
$l['resolves_to'] = "Host Name:";
$l['if_resolvable'] = "(nếu giải quyết được)";
$l['admin_options'] = "Tùy chọn cho Admin:";
$l['search_regip_users'] = "Tìm kiếm thành viên đã đăng kí bằng IP này";
$l['search_postip_users'] = "Tìm kiếm thành viên đã viết bài bằng IP này";
$l['lookup'] = "[tìm]";
$l['member_online_today'] = "<strong>1</strong> thành viên đã online hôm nay";
$l['members_were_online_today'] = "<strong>{1}</strong> thành viên đã online hôm nay";
$l['member_online_hidden'] = " ({1} Ẩn danh)";
$l['members_online_hidden'] = " ({1} Ẩn danh)";
$l['rating_thread'] = "Đang đánh giá chủ đề";
$l['viewing_imcenter'] = "Đang xem IM Center";
$l['managing_favorites'] = "Đang quản lí chủ đề yêu thích";
$l['managing_subscriptions'] = "Đang quản lí chủ đề đang theo dõi";
$l['managing_group'] = "Đang quản lí một nhóm thành viên";
$l['viewing_modcp'] = "Đang xem Moderator CP";
$l['viewing_modlogs'] = "Đang xem nhật kí của Moderator";
$l['managing_announcements'] = "Đang quản lí thông báo";
$l['search_for_user'] = "Tìm kiếm thành viên";
$l['managing_warninglogs'] = "Đang quản lí nhật kí của các cảnh báo";
$l['searching_ips'] = "Đang tìm IP";
$l['viewing_reports'] = "Đang xem các bài viết bị báo cáo";
$l['adding_announcement'] = "Đang thêm thông báo";
$l['deleting_announcement'] = "Đang xóa thông báo";
$l['editing_announcement'] = "Đang chỉnh sửa một thông báo";
$l['managing_modqueue'] = "Đang quản lí Moderation Queue";
$l['editing_user_profiles'] = "Đang chỉnh sửa hồ sơ thành viên";
$l['managing_bans'] = "Đang quản lí các lệnh cấm";
$l['revoking_warning'] = "Đang thu hồi một cảnh cáo";
$l['warning_user'] = "Đang cảnh cáo một thành viên";
$l['viewing_warning'] = "Đang xem một sự cảnh cáo";
$l['managing_warnings'] = "Đang quản lí các lời cảnh cáo";
$l['changing_dst'] = "Đang thay đổi DST Switch";
$l['printing_thread'] = "Đang in một chủ đề";
$l['printing_thread2'] = "Đang in chủ đề <a href=\"{1}\">{2}</a>";
$l['managing_buddyignorelist'] = "Đang quản lí danh sách bạn bè/từ chối";
?>